
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftOPERADOR_CONCATleftOPERADOR_ARITMETICOleftOPERADOR_LOGICOALEATORIO ATRIBUICAO COLCHETES_DIR COLCHETES_ESQ DOIS_PONTOS ENTRADA ESCREVER FIM FUNCAO IDENTIFICADOR INTERPOLATED_STRING NUMERO OPERADOR_ARITMETICO OPERADOR_CONCAT OPERADOR_LOGICO PARENTESES_DIR PARENTESES_ESQ PONTO_E_VIRGULA STRING VIRGULAprogram : statementsstatements : statements statementstatements : statementstatement : ESCREVER PARENTESES_ESQ expression PARENTESES_DIR PONTO_E_VIRGULAstatement : IDENTIFICADOR ATRIBUICAO expression PONTO_E_VIRGULAexpression : expression OPERADOR_ARITMETICO expressionexpression : expression OPERADOR_CONCAT expressionexpression : PARENTESES_ESQ expression PARENTESES_DIRexpression : NUMEROexpression : IDENTIFICADORexpression : STRINGexpression : INTERPOLATED_STRINGexpression : ENTRADA PARENTESES_ESQ PARENTESES_DIRexpression : ALEATORIO PARENTESES_ESQ expression PARENTESES_DIR'
    
_lr_action_items = {'ESCREVER':([0,2,3,6,24,26,],[4,4,-3,-2,-5,-4,]),'IDENTIFICADOR':([0,2,3,6,7,8,9,20,21,23,24,26,],[5,5,-3,-2,12,12,12,12,12,12,-5,-4,]),'$end':([1,2,3,6,24,26,],[0,-1,-3,-2,-5,-4,]),'PARENTESES_ESQ':([4,7,8,9,15,16,20,21,23,],[7,9,9,9,22,23,9,9,9,]),'ATRIBUICAO':([5,],[8,]),'NUMERO':([7,8,9,20,21,23,],[11,11,11,11,11,11,]),'STRING':([7,8,9,20,21,23,],[13,13,13,13,13,13,]),'INTERPOLATED_STRING':([7,8,9,20,21,23,],[14,14,14,14,14,14,]),'ENTRADA':([7,8,9,20,21,23,],[15,15,15,15,15,15,]),'ALEATORIO':([7,8,9,20,21,23,],[16,16,16,16,16,16,]),'PARENTESES_DIR':([10,11,12,13,14,18,22,25,27,28,29,30,31,],[19,-9,-10,-11,-12,25,29,-8,-6,-7,-13,31,-14,]),'OPERADOR_ARITMETICO':([10,11,12,13,14,17,18,25,27,28,29,30,31,],[20,-9,-10,-11,-12,20,20,-8,-6,20,-13,20,-14,]),'OPERADOR_CONCAT':([10,11,12,13,14,17,18,25,27,28,29,30,31,],[21,-9,-10,-11,-12,21,21,-8,-6,-7,-13,21,-14,]),'PONTO_E_VIRGULA':([11,12,13,14,17,19,25,27,28,29,31,],[-9,-10,-11,-12,24,26,-8,-6,-7,-13,-14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,],[2,]),'statement':([0,2,],[3,6,]),'expression':([7,8,9,20,21,23,],[10,17,18,27,28,30,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','main.py',197),
  ('statements -> statements statement','statements',2,'p_statements_multiple','main.py',201),
  ('statements -> statement','statements',1,'p_statements_single','main.py',205),
  ('statement -> ESCREVER PARENTESES_ESQ expression PARENTESES_DIR PONTO_E_VIRGULA','statement',5,'p_statement_escrever','main.py',209),
  ('statement -> IDENTIFICADOR ATRIBUICAO expression PONTO_E_VIRGULA','statement',4,'p_statement_atribuicao','main.py',213),
  ('expression -> expression OPERADOR_ARITMETICO expression','expression',3,'p_expression_binop','main.py',217),
  ('expression -> expression OPERADOR_CONCAT expression','expression',3,'p_expression_concat','main.py',221),
  ('expression -> PARENTESES_ESQ expression PARENTESES_DIR','expression',3,'p_expression_group','main.py',225),
  ('expression -> NUMERO','expression',1,'p_expression_number','main.py',229),
  ('expression -> IDENTIFICADOR','expression',1,'p_expression_identificador','main.py',233),
  ('expression -> STRING','expression',1,'p_expression_string','main.py',237),
  ('expression -> INTERPOLATED_STRING','expression',1,'p_expression_interpolated_string','main.py',241),
  ('expression -> ENTRADA PARENTESES_ESQ PARENTESES_DIR','expression',3,'p_expression_input','main.py',264),
  ('expression -> ALEATORIO PARENTESES_ESQ expression PARENTESES_DIR','expression',4,'p_expression_random','main.py',268),
]
